In [9]:
import pandas as pd
import numpy as np

In [2]:
#load in the grainsize timeseries
GS = pd.read_excel('../data/GrainSize/FRF_GrainSize.xlsx')
#print(GS.info())
GS.head()

Year  Month  Day  xFRF_m  yFRF_m    d10_mm    d25_mm    d50_mm    d75_mm  \
0  2019     10   23      60     960  0.178825  0.213750  0.256512  0.304667   
1  2019     10   23      63     960  0.147380  0.193518  0.281950  0.361614   
2  2019     10   23      66     960  0.179093  0.239900  0.303989  0.368900   
3  2019     10   23      69     960  0.263261  0.305400  0.357083  0.416362   
4  2019     10   23      72     960  0.140110  0.180164  0.238270  0.299050   

     d90_mm  
0  0.353318  
1  0.434300  
2  0.435100  
3  0.479047  
4  0.358365

In [11]:
#open text file of the scene based on the Year, Month, Day
#for examples: ../data/AeolisGrids/ML_grids/20191023.txt
GS['gridname'] = '../data/AeolisGrids/ML_grids/' + GS['Year'].astype('string') + GS['Month'].astype('string') +  GS['Day'].astype('string') +'.txt'
GS['gridname'][0]


'../data/AeolisGrids/ML_grids/20191023.txt'

In [16]:
grid = np.loadtxt(GS['gridname'][0])
print(grid)
print(grid.shape)

[[0. 0. 0. ... 3. 3. 3.]
 [0. 0. 0. ... 3. 3. 3.]
 [0. 0. 0. ... 3. 3. 3.]
 ...
 [0. 0. 3. ... 3. 3. 3.]
 [0. 0. 3. ... 3. 3. 3.]
 [0. 0. 3. ... 3. 3. 3.]]
(251, 81)


In [20]:
#find the class of the pixel at (xFRF_m, yFRF_m).. 

#First create the look up table to find the right index
xgrid =np.loadtxt('../data/AeolisGrids/x.txt')
ygrid =np.loadtxt('../data/AeolisGrids/y.txt')

#get first row of x.. this tells you what column to be in
xdim = xgrid[0, :]
#take first column of y . this tells you what row to be in
ydim = ygrid[:, 0]

print(xdim)
print(ydim)

[ 40.  41.  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.
  54.  55.  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.
  68.  69.  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.
  82.  83.  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.
  96.  97.  98.  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109.
 110. 111. 112. 113. 114. 115. 116. 117. 118. 119. 120.]
[ 800.  801.  802.  803.  804.  805.  806.  807.  808.  809.  810.  811.
  812.  813.  814.  815.  816.  817.  818.  819.  820.  821.  822.  823.
  824.  825.  826.  827.  828.  829.  830.  831.  832.  833.  834.  835.
  836.  837.  838.  839.  840.  841.  842.  843.  844.  845.  846.  847.
  848.  849.  850.  851.  852.  853.  854.  855.  856.  857.  858.  859.
  860.  861.  862.  863.  864.  865.  866.  867.  868.  869.  870.  871.
  872.  873.  874.  875.  876.  877.  878.  879.  880.  881.  882.  883.
  884.  885.  886.  887.  888.  889.  890.  891.  892.  893.  894.  895.
  89

In [26]:
#grab the index of the array based on these look up tables.. 
#so here it is 60, 960 in this case.
Xwhere = np.where(xdim==60)[0][0]
Ywhere = np.where(ydim==960)[0][0]

print(Xwhere)
print(Ywhere)

20
160


In [28]:
#pull that value out of the array
# 0,1 use sand    -- (0 = vegetation, 1 = sand,)
# 2,3 use coarse  -- (2 = coarse sediment, 3 = water)
Graincat = grid[Ywhere,Xwhere]
print(Graincat)

1.0


In [ ]:
# put that value in the dataframe

In [ ]:
#write a loop

In [ ]:
#make a box plot

Scraps

In [3]:
#just to look at the unique values
GS['ymd'] = GS['Year'].astype('string') +'_' + GS['Month'].astype('string') +'_' +  GS['Day'].astype('string')
sceneArray = GS['ymd'].unique()
scenes = pd.DataFrame(sceneArray,columns = ['ymd_ListofScenes'] )
scenes.head()

ymd_ListofScenes
0       2019_10_23
1       2019_10_30
2        2019_11_7
3       2019_11_14
4       2019_11_21